### ISSUE TITLE
Generating tests for child properties

### ISSUE THREAD

**Issue by doctyper** [doctyper/reflexie#16]
Running into a brick wall with generating unit tests. Basically, the spec is huge and in order to fully test the spec I need to generate tests for one property, and every other property that interacts with said property.

Turns out this generates well over 700,000 tests. Browsers simply cannot handle that.

Additionally, several properties need multiple tests, for different units of measurement, different ways of interacting with flex, etc.

Not sure what the best way of handling this is. Thoughts?

**Comment by jonrimmer** [comment]
One technique to deal with combinatorial explosion in testing is _pairwise_ testing. If you Google for it you'll find quite a few explainers, most of which are kinda math heavy, but [this one is nice and straightfoward](http://blogs.msdn.com/b/davfries/archive/2004/06/17/158900.aspx). Basically, it arises from the observation that, statistically speaking, most software flaws arise from a combination of just two parameters, rather than three, four, or more. So, by ensuring you test all possible pairs of values, rather than every combination of every value, you can drastically reduce your testcases while still ensuring decent coverage.

**Comment by doctyper** [comment]
Interesting, thanks for weighing in. I'll have to delve into pairwise testing.

**Comment by doctyper** [comment]
Closed via 0e6f4b9a84. Thanks @JonRimmer for the point in the right direction!
